name: CI for act CLI
on:
  - push
  - workflow_dispatch
env:
  RUBY_VERSION: 3.1.0
  NODE_VERSION: 16.13.1
  RAILS_ENV: test
  TZ: '/usr/share/zoneinfo/Asia/Tokyo'
jobs:
  ci:
    strategy:
      fail-fast: false # ある Job が Fail しても、他の Job がキャンセルされないようにする
      matrix:
        os: [ubuntu-latest] # [ubuntu-latest, macos-latest]
    name: act用（ローカルデバッグ用）CI
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: GitHub Actions の実行環境の確認
        id: check_on_act_or_not
        # /opt/hostedtoolcache は act のイメージにしか存在しないことを前提としている
        run: |
          OPT_DIRECTORY_LIST=$(/bin/ls /opt)
          if [[ "$OPT_DIRECTORY_LIST" =~ hostedtoolcache ]]; then IS_EXECUTION_ON_ACT="TRUE"; else IS_EXECUTION_ON_ACT="FALSE"; fi

          echo "::set-output name=is_execution_on_act::${IS_EXECUTION_ON_ACT}"
      - name: 「act（ローカルCLI）での実行環境」の場合だけ実行される
        if: ${{ steps.check_on_act_or_not.outputs.is_execution_on_act == 'TRUE' }}
        run: |
          echo '「act（ローカルCLI）での実行環境」で実行中です！'
      - name: 「非actでの実行環境」の場合だけ実行される
        if: ${{ steps.check_on_act_or_not.outputs.is_execution_on_act != 'TRUE' }}
        run: |
          echo '「非actでの実行環境」で実行中です！'
