name: CI for act CLI
on:
  - push
  - workflow_dispatch
env:
  RUBY_VERSION: 3.1.0
  NODE_VERSION: 16.13.1
  RAILS_ENV: test
  TZ: '/usr/share/zoneinfo/Asia/Tokyo'
jobs:
  ci:
    strategy:
      fail-fast: false # ある Job が Fail しても、他の Job がキャンセルされないようにする
      matrix:
        os: [ubuntu-latest] # [ubuntu-latest, macos-latest]
    name: act用（ローカルデバッグ用）CI
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: 環境の確認
        id: this_environments
        run: |
          echo "::set-output name=hostname::$(hostname)"
      - name: 「act環境」の場合だけ実行される
        if: ${{ steps.this_environments.outputs.hostname == 'docker-desktop' }}
        run: |
          echo '「act環境」で実行中です！'
      - name: 「非act環境」の場合だけ実行される
        if: ${{ steps.this_environments.outputs.hostname != 'docker-desktop' }}
        run: |
          echo '「非act環境」で実行中です！'
